name = input("Enter your name:")
age = int(input("Enter your age:"))
course_code = input("Enter your course code:")
print(f" Name: {name}")
print(f" Age: {age} ")
print(f" Course code: {course_code} ")
print (type(name))
print (type(age))
print (type(course_code))